// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpryeLY8m4opqvND520iYUJum7SyMrXA',
    appId: '1:675479997488:web:ef675ba5db04636ab631f5',
    messagingSenderId: '675479997488',
    projectId: 'gadgethive-e6df8',
    authDomain: 'gadgethive-e6df8.firebaseapp.com',
    storageBucket: 'gadgethive-e6df8.appspot.com',
    measurementId: 'G-27KTMRF9S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGX_bGQu2PhhPK8V-VbmUG_NLRCf45k8',
    appId: '1:675479997488:android:34affbf64e61ea99b631f5',
    messagingSenderId: '675479997488',
    projectId: 'gadgethive-e6df8',
    storageBucket: 'gadgethive-e6df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gJV12_S7vnBde2dbMJAY63xBlQ0H-wA',
    appId: '1:675479997488:ios:a03635f93dda2380b631f5',
    messagingSenderId: '675479997488',
    projectId: 'gadgethive-e6df8',
    storageBucket: 'gadgethive-e6df8.appspot.com',
    iosClientId: '675479997488-idnqplvde37qddqqr1np6b2p7asqpunu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gadgethive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5gJV12_S7vnBde2dbMJAY63xBlQ0H-wA',
    appId: '1:675479997488:ios:a03635f93dda2380b631f5',
    messagingSenderId: '675479997488',
    projectId: 'gadgethive-e6df8',
    storageBucket: 'gadgethive-e6df8.appspot.com',
    iosClientId: '675479997488-idnqplvde37qddqqr1np6b2p7asqpunu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gadgethive',
  );
}
